export const EMPRESA_SELECTED = 'EMPRESA_SELECTED';

export const INPUT_EMPRESA_CHANGED = 'INPUT_EMPRESA_CHANGED';

export const INPUT_PERIODO_CHANGED = 'INPUT_PERIODO_CHANGED';

export const AGREGAR_PERIODO = 'AGREGAR_PERIODO';

export const INPUT_ANIO_CHANGED = 'INPUT_AÑO_CHANGED';
