export const INITIAL_DATA_REQUEST = 'INITIAL_DATA_REQUEST';
export const INITIAL_DATA_SUCCESS = 'INITIAL_DATA_SUCCESS';

export const SAVE_EMPRESA_REQUEST = 'SAVE_EMPRESA_REQUEST';
export const SAVE_EMPRESA_SUCCESS = 'SAVE_EMPRESA_SUCCESS';
